#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DIST_DIR="${ROOT_DIR}/dist"
OUT_FILE="${DIST_DIR}/gpu_watchdog.py"

mkdir -p "${DIST_DIR}"

python3 - "${ROOT_DIR}" "${OUT_FILE}" <<'PY'
from __future__ import annotations

import json
import sys
from pathlib import Path


root_dir = Path(sys.argv[1])
out_file = Path(sys.argv[2])

module_files = {
    "nvsmi": root_dir / "nvsmi.py",
    "gpu_watchdog_core": root_dir / "gpu_watchdog_core" / "__init__.py",
}

for path in sorted((root_dir / "gpu_watchdog_core").glob("*.py")):
    if path.name == "__init__.py":
        continue
    module_files[f"gpu_watchdog_core.{path.stem}"] = path

sources = {}
for module_name, path in module_files.items():
    if not path.exists():
        raise SystemExit(f"missing source file: {path}")
    sources[module_name] = path.read_text(encoding="utf-8")

bootstrap = f'''#!/usr/bin/env python3
"""Single-file GPU Watchdog bundle generated by build.sh."""

from __future__ import annotations

import importlib.abc
import importlib.machinery
import sys

# place embedded config here for real one file distribution, can be overridden by --config or ./config.json
EMBEDDED_CONFIG="""

""".strip()

_SOURCES = {json.dumps(sources, ensure_ascii=False, indent=2)}
_PACKAGES = {{"gpu_watchdog_core"}}


class _BundledLoader(importlib.abc.Loader):
    def create_module(self, spec):
        return None

    def exec_module(self, module):
        fullname = module.__spec__.name
        source = _SOURCES[fullname]
        module.__file__ = f"<gpu-watchdog-bundle>/{{fullname.replace('.', '/')}}.py"
        if fullname in _PACKAGES:
            module.__package__ = fullname
            module.__path__ = []
        else:
            module.__package__ = fullname.rpartition(".")[0]
        exec(compile(source, module.__file__, "exec"), module.__dict__)


class _BundledFinder(importlib.abc.MetaPathFinder):
    def find_spec(self, fullname, path=None, target=None):
        if fullname not in _SOURCES:
            return None
        is_package = fullname in _PACKAGES
        spec = importlib.machinery.ModuleSpec(fullname, _BundledLoader(), is_package=is_package)
        if is_package:
            spec.submodule_search_locations = []
        return spec


def _install_importer():
    if not any(isinstance(finder, _BundledFinder) for finder in sys.meta_path):
        sys.meta_path.insert(0, _BundledFinder())


def main(argv=None):
    _install_importer()
    from gpu_watchdog_core import cli as cli_module

    cli_module.EMBEDDED_CONFIG = EMBEDDED_CONFIG
    return cli_module.main(argv)


if __name__ == "__main__":
    raise SystemExit(main())
'''

out_file.write_text(bootstrap, encoding="utf-8")
out_file.chmod(0o755)
PY

python3 - "${OUT_FILE}" <<'PY'
from __future__ import annotations

import sys
from pathlib import Path


path = Path(sys.argv[1])
compile(path.read_text(encoding="utf-8"), str(path), "exec")
PY
python3 "${OUT_FILE}" --help >/dev/null
python3 "${OUT_FILE}" --samples >/dev/null 2>&1

TEST_CONFIG="$(mktemp)"
trap 'rm -f "${TEST_CONFIG}"' EXIT
printf '{"interval_seconds": 1, "cooldown_seconds": 1, "rules": []}\n' >"${TEST_CONFIG}"
python3 "${OUT_FILE}" --config "${TEST_CONFIG}" --once

echo "Built and tested ${OUT_FILE}"
